apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: sunshine2050/cloud-devops-engineer-capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80